### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by benmccann** [lightbend/paradox#100] opened 2017-03-20 05:03 UTC
We should add docs validation. This functionality can be found already implemented in [LightbendMarkdownValidation](https://github.com/typesafehub/lightbend-markdown/blob/master/plugin/src/main/scala/com/lightbend/markdown/sbt/LightbendMarkdownValidation.scala) and [PlayDocsValidation](https://github.com/playframework/playframework/blob/master/framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala). This is a pre-requisite for Play and/or Lagom moving to Paradox one day. The validation on Play and Lagom's docs catches a lot of errors during development.

**Comment by eed3si9n** [comment] 2017-03-20 22:30
I think this is a duplicate of #53. You're welcome to comment on the issue to add more context.

**Closed by eed3si9n** 2017-03-20 22:30 UTC
