### ISSUE TITLE
Customize how newlines are rendered

### ISSUE THREAD

**Issue by evacchi** [lightbend/paradox#38] opened 2016-10-21 15:20 UTC
Currently newlines introduce `<br>`s. Is it possible to customize it/make it follow [basic MD behavior](https://daringfireball.net/projects/markdown/syntax#p), i.e., hard breaks are inserted only when the line terminates with >2 spaces ?

**Comment by dwijnand** [comment] 2016-10-21 15:46
Duplicate of #31

**Closed by dwijnand** 2016-10-21 15:46 UTC

**Comment by eed3si9n** [comment] 2016-10-21 15:48
There is a version with the fix, but it's buggy so let me push another release out with more fixes.

**Comment by evacchi** [comment] 2016-10-22 20:31
sure, thanks!
