### ISSUE TITLE
group/tab not rendered if inline snippet contains empty line

### ISSUE THREAD

**Issue by patriknw** [lightbend/paradox#224] opened 2018-07-13 11:28 UTC
Reproducer

```
sbt
:   ```
    addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc" % "0.1")

    enablePlugins(AkkaGrpcPlugin)
    ```
```

Removing the empty line and it's fine.
Adding 4 space indentation to the empty line doesn't help.

**Comment by jonas** [comment] 2018-07-13 16:24
Duplicate of #161 ?

**Comment by 2m** [comment] 2018-07-18 12:06
Yup. Looks like a duplicate.

**Closed by 2m** 2018-07-18 12:06 UTC
